version: '3.8'

services:

  foundry:
    build:
      context: .
      dockerfile: Dockerfile.foundry
    container_name: foundry-dev
    volumes:
      # Mount source code for live development
      - ./src:/app/src
      - ./script:/app/script
      # Mount foundry config files
      - ./foundry.toml:/app/foundry.toml
      # Persist forge cache and build artifacts
      - foundry-cache:/app/cache
      - foundry-out:/app/out
      # Keystore
      - ~/.foundry/keystores:/home/foundry/.foundry/keystores  # Mount keystore directory
      - ./.password:/app/.password  # Mount password file
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - FOUNDRY_PROFILE=default
    command: bash
    networks:
      - foundry-network
    depends_on:
      anvil:
        condition: service_healthy # Wait for anvil to be healthy

  anvil:
    build:
      context: .
      dockerfile: Dockerfile.anvil
    container_name: foundry-anvil
    ports:
      - "8545:8545"
    command: ["--host", "0.0.0.0", "--port", "8545", "--fork-url", "${SEPOLIA_RPC_URL}"]
    networks:
      - foundry-network
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:8545"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  foundry-cache:
  foundry-out:

networks:
  foundry-network:
    driver: bridge